{% set name = "django-rest-auth" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f11e12175dafeed772f50d740d22caeab27e99a3caca24ec65e66a8d6de16571

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - django >=1.8.0
    - djangorestframework >=3.1.3
    - pip
    - python
    - six >=1.9.0
  run:
    - django >=1.8.0
    - djangorestframework >=3.1.3
    - python
    - six >=1.9.0

test:
  imports:
    - rest_auth
    - rest_auth.registration
    - rest_auth.tests
  requires:
    - django-allauth >=0.25.0
    - djangorestframework-jwt >=1.9.0
    - responses >=0.5.0

about:
  home: http://github.com/Tivix/django-rest-auth
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create a set of REST API endpoints for Authentication and Registration

extra:
  recipe-maintainers:
    - bgruening
