travis:
  secure:
    BINSTAR_TOKEN: YxRmmf8UDR7OP8bu91cnSqBNXDXgnbvb9wEzq/8BtIldOB4aTMMRbxLBJYcEAiIXNbLbvAzeE+tK0m7moawbMLDnyLpyYg7LKHkaeMXBIlMgag3MsNaoGB6rA6xhBq4xW6rDRHHFA9fpknLTRNehQfVJpgeR0Y3YNyi4THSwiGQO5fUV0rCXxnd9mGZIlON8GEyIexy6vUkUzE3IL1fSbgn0ImPi1wB52pIQg4OQqzNlNX0pwvdz6qaw0nUVya/CNe+pOL1DTxP/UyzFv0v960UUxOELabKrxrgqv1s6s0H5cd1Y890n2k4hdWX4FJ2qCwWI0yiU9l4S6lQd4nDlIFIhDxrJ76P+3soZ4G8NPqXTB7q9kJiKoa1kvt8cNGCEv1EHnw7XWagKePQJkRz/wDzYcqXT2Mlmzsq/gcFY0ghwMoAUtDK4gjRTHKRlM0i/cRtQ65/FaWUG7XodysSW4murQL+9BtVzj2Cfh0AWpBizwkotx/aR5dT6NVjOpw1eObpTt/BkMlO6vxNiObTW9vm3o/S8gpIJWLDowJ7YGNELqwZCSI0RSHAA43+B1qxUuGTkgIGdyGfOskrHeqmNFsjWfMx7wh6JviwBUYSkz6FON/aIgqp2wqcM5r5+3bxK2aGeWhwSBzXX0+oQgBvr5JRDa9QkUESt2eHmO44uXQs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
